curl -X GET \
  'https://graph.instagram.com/MEDIAIDHERE?fields=caption,id,media_type,media_url,thumbnail_url,timestamp,username&access_token=IGQVJYeWUwMGQydGNiTGN4ZAGxwc01PVlhRR3EycDF1LVVlNXlfZA0RTV3FBT3pqbE1tYWdNRUpDSWttR1A1NmdVRUlBOTdLNm1XUlpkWUhEMWVSMDNOUGFmQTBLenlpMEFCUVNXR0xn